// <copyright file="Test.cs" company="Isopoh">
// To the extent possible under law, the author(s) have dedicated all copyright
// and related and neighboring rights to this software to the public domain
// worldwide. This software is distributed without any warranty.
// </copyright>

namespace Argon2TestVector
{
    using Argon2TestVectorType;
    using System.Collections.Generic;

    /// <summary>
    /// Holds Argon2 test vectors generated from the reference C implementation.
    /// </summary>
    public static partial class Test
    {
        /// <summary>
        /// Gets Argon2 vectors generated by the reference C implementation.
        /// </summary>
        public static List<TestVector> Argon2Vectors => GetTestVectors();

        static partial void LoadTestVectors(List<TestVector> testVectors);

        private static List<TestVector> GetTestVectors()
        {
            var ret = new List<TestVector>();
            LoadTestVectors(ret);
            return ret;
        }
    }
}